from django import forms


class LogInForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'shadow mb-2',
                                                           'placeholder': "Електронна адреса"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'shadow',
                                                                 'placeholder': 'Пароль',
                                                                 'id': 'password'}))


class SignUpForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'shadow m-1',
                                                           'placeholder': "Електронна адреса"}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow m-1',
                                                                 'placeholder': "Номер телефону"}),
                                   max_length=13,
                                   required=True)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow m-1',
                                                               'placeholder': "Ім'я"}),
                                 max_length=30,
                                 required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow m-1',
                                                              'placeholder': "Прізвище"}),
                                max_length=30,
                                required=True)
    patronymic = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow m-1',
                                                               'placeholder': "По-батькові"}),
                                 max_length=30,
                                 required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'shadow', 'placeholder': 'Пароль',
                                                                  'id': 'password1'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'shadow',
                                                                  'placeholder': 'Повторіть пароль',
                                                                  'id': 'password2'}))


class CardForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow m-1',
                                                          'placeholder': 'Назва картки',
                                                          'maxlength': '30'}))
    bank_account = forms.ChoiceField(widget=forms.Select(attrs={'class': 'shadow m-1 dropdown dropdown-menu-dark'}),
                                     choices=[('', 'Виберіть рахунок')])
    color = forms.ChoiceField(widget=forms.Select(attrs={'class': 'shadow m-1 dropdown dropdown-menu-dark'}),
                              choices=[('', 'Виберіть колір'), ('cyan', 'Бірюзовий'), ('yellow', 'Жовтий'),
                                       ('green', 'Зелений'), ('orange', 'Помаранчевий'), ('magenta', 'Пурпурний'),
                                       ('blue', 'Cиній'), ('grey', 'Сірий'), ('purple', 'Фіолетовий'),
                                       ('red', 'Червоний')])
    payment_system = forms.ChoiceField(widget=forms.Select(attrs={'class': 'shadow m-1 dropdown dropdown-menu-dark'}),
                                       choices=[('', 'Виберіть платіжну систему'), ('mastercard', 'Mastercard'), ('visa', 'Visa')])


class BankAccountForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow my-1',
                                                          'placeholder': 'Назва рахунку',
                                                          'maxlength': '30'}))

    currency = forms.ChoiceField(widget=forms.Select(attrs={'class': 'dropdown dropdown-menu-dark my-1'}),
                                 choices=[('UAH', 'Українська гривня (UAH)'),
                                          ('USD', 'Американський долар (USD)'),
                                          ('EUR', 'Євро (EUR)'),
                                          ('CAD', 'Канадський Долар (CAD)'),
                                          ('CHF', 'Швейцарський Франк (CHF)'),
                                          ('CNY', 'Китайський Юань (CNY)'),
                                          ('CZK', 'Чеська Крона (CZK)'),
                                          ('DKK', 'Данська Крона (DKK)'),
                                          ('GBP', 'Фунт Стерлінгів (GBP)'),
                                          ('HUF', 'Угорський форинт (HUF)'),
                                          ('ILS', 'Новий Ізраїльський Шекель (ILS)'),
                                          ('JPY', 'Японська єна (JPY)'),
                                          ('KZT', 'Казахстанський теньге (KZT)'),
                                          ('MDL', 'Молдовський Лей (MDL)'),
                                          ('NOK', 'Норвезька Крона (NOK)'),
                                          ('PLN', 'Польський злотий (PLN)'),
                                          ('SEK', 'Шведська Крона (SEK)'),
                                          ('SGD', 'Сингапурський Долар (SGD)'),
                                          ('TRY', 'Турецька Ліра (TRY)'),
                                          ('UZS', 'Узбекський Сум (UZS)'),
                                          ('BGN', 'Болгарський лев (BGN)'),
                                          ('RON', 'Новий румунський лей (RON)'),
                                          ('ISK', 'Ісландська крона (ISK)'),
                                          ('HRK', 'Хорватська куна (HRK)'),
                                          ('AUD', 'Австралійський долар (AUD)'),
                                          ('BRL', 'Бразильський реал (BRL)'),
                                          ('HKD', 'Гонконгівський долар (HKD)'),
                                          ('IDR', 'Індонезійська рупія (IDR)'),
                                          ('INR', 'Індійська рупія (INR)'),
                                          ('KRW', 'Піденно-корейська вона (KRW)'),
                                          ('MXN', 'Мексиканське песо (MXN)'),
                                          ('MYR', 'Малайзійський рингіт (MYR)'),
                                          ('NZD', 'Новозеландський долар (NZD)'),
                                          ('PHP', 'Філіппінське песо (PHP)'),
                                          ('THB', 'Таїландський бат (THB)'),
                                          ('ZAR', 'Південно-африканський ренд (ZAR)'),
                                          ('AED', 'Дирхам ОАЕ (AED)'),
                                          ('AFN', 'Афганський афгані (AFN)'),
                                          ('ALL', 'Албанський лек (ALL)'),
                                          ('ARS', 'Аргентинський песо (ARS)'),
                                          ('BAM', 'Конвертовна марка (BAM)'),
                                          ('BBD', 'Барбадоський долар (BBD)'),
                                          ('BDT', 'Бангладеська така (BDT)'),
                                          ('BHD', 'Бахрейнський динар (BHD)'),
                                          ('BIF', 'Бурундійський франк (BIF)'),
                                          ('BMD', 'Бермудський долар (BMD)'),
                                          ('BND', 'Брунейський долар (BND)'),
                                          ('BOB', 'Болівійський болівіано (BOB)'),
                                          ('BSD', 'Багамський долар (BSD)'),
                                          ('BWP', 'Ботсванська пула (BWP)'),
                                          ('BZD', 'Белізький долар (BZD)'),
                                          ('CLP', 'Чилійське песо (CLP)'),
                                          ('COP', 'Колумбійське песо (COP)'),
                                          ('CRC', 'Костаріканський колон (CRC)'),
                                          ('CUP', 'Кубинське песо (CUP)'),
                                          ('CVE', 'Еску́до Кабо-Верде (CVE)'),
                                          ('DJF', 'Джибутійський франк (DJF)'),
                                          ('DOP', 'Домініканський песо (DOP)'),
                                          ('DZD', 'Алжирський динар (DZD)'),
                                          ('EGP', 'Єгипетський фунт (EGP)'),
                                          ('ETB', 'Ефіопський бир (ETB)'),
                                          ('FJD', 'Фіджійський долар (FJD)'),
                                          ('GHS', 'Ганський седі (GHS)'),
                                          ('GNF', 'Гвінейський франк (GNF)'),
                                          ('GTQ', 'Гватемальський кецаль (GTQ)'),
                                          ('HNL', 'Гондураська лемпір (HNL)'),
                                          ('HTG', 'Гаїтянський гурд (HTG)'),
                                          ('IQD', 'Іракський динар (IQD)'),
                                          ('JMD', 'Ямайський долар (JMD)'),
                                          ('JOD', 'Іорданський динар (JOD)'),
                                          ('KES', 'Кенійський шилінг (KES)'),
                                          ('KHR', 'Камбоджийський ріел (KHR)'),
                                          ('KWD', 'Кувейтський динар (KWD)'),
                                          ('KYD', 'Долар Кайманових Островів (KYD)'),
                                          ('LAK', 'Лаоський кіп (LAK)'),
                                          ('LBP', 'Ліванський фунт (LBP)'),
                                          ('LKR', 'Шрі-ланкійська рупія (LKR)'),
                                          ('LSL', 'Лоті Лесото (LSL)'),
                                          ('LYD', 'Лівійський динар (LYD)'),
                                          ('MAD', 'Мароканський дирхам (MAD)'),
                                          ('MGA', 'Малагасійський аріарі (MGA)'),
                                          ('MKD', 'Македонський денар (MKD)'),
                                          ('MMK', "М'янмський к'ят (MMK)"),
                                          ('MOP', 'Аоминська патака (MOP)'),
                                          ('MUR', 'Маврикійська рупія (MUR)'),
                                          ('MVR', 'Мальдівська руфія (MVR)'),
                                          ('MWK', 'Малавійська квача (MWK)'),
                                          ('NAD', 'Намібійський долар (NAD)'),
                                          ('NGN', 'Нігерійська найра (NGN)'),
                                          ('NIO', 'Нікараґуанська кордоба (NIO)'),
                                          ('NPR', 'Непальська рупія (NPR)'),
                                          ('OMR', 'Оманський ріал (OMR)'),
                                          ('PAB', 'Панамське бальбоа (PAB)'),
                                          ('PEN', 'Перуанський соль (PEN)'),
                                          ('PGK', 'Кіна Папуа Нової Гвінеї (PGK)'),
                                          ('PKR', 'Пакістанська рупія (PKR)'),
                                          ('PYG', 'Парагвайський ґуарані (PYG)'),
                                          ('QAR', 'Катарський ріал (QAR)'),
                                          ('RSD', 'Сербський динар (RSD)'),
                                          ('RWF', 'Руандійський франк (RWF)'),
                                          ('SAR', 'Саудівський ріал (SAR)'),
                                          ('SCR', 'Сейшельська рупія (SCR)'),
                                          ('SOS', 'Сомалійський шилінг (SOS)'),
                                          ('SVC', 'Сальвадорський колон (SVC)'),
                                          ('SZL', 'Свазілендський ліланґені (SZL)'),
                                          ('TND', 'Туніський динар (TND)'),
                                          ('TTD', 'Долар Тринідаду і Тобаго (TTD)'),
                                          ('TWD', 'Тайванський долар (TWD)'),
                                          ('TZS', 'Танзанійський шилінг (TZS)'),
                                          ('UGX', 'Угандійський шилінг (UGX)'),
                                          ('UYU', 'Уругвайське песо (UYU)'),
                                          ('VND', "В'єтнамський донг (VND)"),
                                          ('XAF', 'Франк КФА (Центральна Африка) (XAF)'),
                                          ('XOF', 'Франк КФА (Західна Африка) (XOF)'),
                                          ('XPF', 'Французький тихоокеанський франк (XPF)'),
                                          ('ZMW', 'Замбійська квача (ZMW)'),
                                          ('RUB', 'Російський рубль (RUB)')])


class ExchangeRateForm(forms.Form):
    currency = forms.ChoiceField(widget=forms.Select(attrs={'class': 'dropdown dropdown-menu-dark',
                                                            'onchange': "this.parentNode.submit()"}),
                                 choices=[('UAH', 'Українська гривня (UAH)'),
                                          ('USD', 'Американський долар (USD)'),
                                          ('EUR', 'Євро (EUR)'),
                                          ('CAD', 'Канадський Долар (CAD)'),
                                          ('CHF', 'Швейцарський Франк (CHF)'),
                                          ('CNY', 'Китайський Юань (CNY)'),
                                          ('CZK', 'Чеська Крона (CZK)'),
                                          ('DKK', 'Данська Крона (DKK)'),
                                          ('GBP', 'Фунт Стерлінгів (GBP)'),
                                          ('HUF', 'Угорський форинт (HUF)'),
                                          ('ILS', 'Новий Ізраїльський Шекель (ILS)'),
                                          ('JPY', 'Японська єна (JPY)'),
                                          ('KZT', 'Казахстанський теньге (KZT)'),
                                          ('MDL', 'Молдовський Лей (MDL)'),
                                          ('NOK', 'Норвезька Крона (NOK)'),
                                          ('PLN', 'Польський злотий (PLN)'),
                                          ('SEK', 'Шведська Крона (SEK)'),
                                          ('SGD', 'Сингапурський Долар (SGD)'),
                                          ('TRY', 'Турецька Ліра (TRY)'),
                                          ('UZS', 'Узбекський Сум (UZS)'),
                                          ('BGN', 'Болгарський лев (BGN)'),
                                          ('RON', 'Новий румунський лей (RON)'),
                                          ('ISK', 'Ісландська крона (ISK)'),
                                          ('HRK', 'Хорватська куна (HRK)'),
                                          ('AUD', 'Австралійський долар (AUD)'),
                                          ('BRL', 'Бразильський реал (BRL)'),
                                          ('HKD', 'Гонконгівський долар (HKD)'),
                                          ('IDR', 'Індонезійська рупія (IDR)'),
                                          ('INR', 'Індійська рупія (INR)'),
                                          ('KRW', 'Піденно-корейська вона (KRW)'),
                                          ('MXN', 'Мексиканське песо (MXN)'),
                                          ('MYR', 'Малайзійський рингіт (MYR)'),
                                          ('NZD', 'Новозеландський долар (NZD)'),
                                          ('PHP', 'Філіппінське песо (PHP)'),
                                          ('THB', 'Таїландський бат (THB)'),
                                          ('ZAR', 'Південно-африканський ренд (ZAR)'),
                                          ('AED', 'Дирхам ОАЕ (AED)'),
                                          ('AFN', 'Афганський афгані (AFN)'),
                                          ('ALL', 'Албанський лек (ALL)'),
                                          ('ARS', 'Аргентинський песо (ARS)'),
                                          ('BAM', 'Конвертовна марка (BAM)'),
                                          ('BBD', 'Барбадоський долар (BBD)'),
                                          ('BDT', 'Бангладеська така (BDT)'),
                                          ('BHD', 'Бахрейнський динар (BHD)'),
                                          ('BIF', 'Бурундійський франк (BIF)'),
                                          ('BMD', 'Бермудський долар (BMD)'),
                                          ('BND', 'Брунейський долар (BND)'),
                                          ('BOB', 'Болівійський болівіано (BOB)'),
                                          ('BSD', 'Багамський долар (BSD)'),
                                          ('BWP', 'Ботсванська пула (BWP)'),
                                          ('BZD', 'Белізький долар (BZD)'),
                                          ('CLP', 'Чилійське песо (CLP)'),
                                          ('COP', 'Колумбійське песо (COP)'),
                                          ('CRC', 'Костаріканський колон (CRC)'),
                                          ('CUP', 'Кубинське песо (CUP)'),
                                          ('CVE', 'Еску́до Кабо-Верде (CVE)'),
                                          ('DJF', 'Джибутійський франк (DJF)'),
                                          ('DOP', 'Домініканський песо (DOP)'),
                                          ('DZD', 'Алжирський динар (DZD)'),
                                          ('EGP', 'Єгипетський фунт (EGP)'),
                                          ('ETB', 'Ефіопський бир (ETB)'),
                                          ('FJD', 'Фіджійський долар (FJD)'),
                                          ('GHS', 'Ганський седі (GHS)'),
                                          ('GNF', 'Гвінейський франк (GNF)'),
                                          ('GTQ', 'Гватемальський кецаль (GTQ)'),
                                          ('HNL', 'Гондураська лемпір (HNL)'),
                                          ('HTG', 'Гаїтянський гурд (HTG)'),
                                          ('IQD', 'Іракський динар (IQD)'),
                                          ('JMD', 'Ямайський долар (JMD)'),
                                          ('JOD', 'Іорданський динар (JOD)'),
                                          ('KES', 'Кенійський шилінг (KES)'),
                                          ('KHR', 'Камбоджийський ріел (KHR)'),
                                          ('KWD', 'Кувейтський динар (KWD)'),
                                          ('KYD', 'Долар Кайманових Островів (KYD)'),
                                          ('LAK', 'Лаоський кіп (LAK)'),
                                          ('LBP', 'Ліванський фунт (LBP)'),
                                          ('LKR', 'Шрі-ланкійська рупія (LKR)'),
                                          ('LSL', 'Лоті Лесото (LSL)'),
                                          ('LYD', 'Лівійський динар (LYD)'),
                                          ('MAD', 'Мароканський дирхам (MAD)'),
                                          ('MGA', 'Малагасійський аріарі (MGA)'),
                                          ('MKD', 'Македонський денар (MKD)'),
                                          ('MMK', "М'янмський к'ят (MMK)"),
                                          ('MOP', 'Аоминська патака (MOP)'),
                                          ('MUR', 'Маврикійська рупія (MUR)'),
                                          ('MVR', 'Мальдівська руфія (MVR)'),
                                          ('MWK', 'Малавійська квача (MWK)'),
                                          ('NAD', 'Намібійський долар (NAD)'),
                                          ('NGN', 'Нігерійська найра (NGN)'),
                                          ('NIO', 'Нікараґуанська кордоба (NIO)'),
                                          ('NPR', 'Непальська рупія (NPR)'),
                                          ('OMR', 'Оманський ріал (OMR)'),
                                          ('PAB', 'Панамське бальбоа (PAB)'),
                                          ('PEN', 'Перуанський соль (PEN)'),
                                          ('PGK', 'Кіна Папуа Нової Гвінеї (PGK)'),
                                          ('PKR', 'Пакістанська рупія (PKR)'),
                                          ('PYG', 'Парагвайський ґуарані (PYG)'),
                                          ('QAR', 'Катарський ріал (QAR)'),
                                          ('RSD', 'Сербський динар (RSD)'),
                                          ('RWF', 'Руандійський франк (RWF)'),
                                          ('SAR', 'Саудівський ріал (SAR)'),
                                          ('SCR', 'Сейшельська рупія (SCR)'),
                                          ('SOS', 'Сомалійський шилінг (SOS)'),
                                          ('SVC', 'Сальвадорський колон (SVC)'),
                                          ('SZL', 'Свазілендський ліланґені (SZL)'),
                                          ('TND', 'Туніський динар (TND)'),
                                          ('TTD', 'Долар Тринідаду і Тобаго (TTD)'),
                                          ('TWD', 'Тайванський долар (TWD)'),
                                          ('TZS', 'Танзанійський шилінг (TZS)'),
                                          ('UGX', 'Угандійський шилінг (UGX)'),
                                          ('UYU', 'Уругвайське песо (UYU)'),
                                          ('VND', "В'єтнамський донг (VND)"),
                                          ('XAF', 'Франк КФА (Центральна Африка) (XAF)'),
                                          ('XOF', 'Франк КФА (Західна Африка) (XOF)'),
                                          ('XPF', 'Французький тихоокеанський франк (XPF)'),
                                          ('ZMW', 'Замбійська квача (ZMW)'),
                                          ('RUB', 'Російський рубль (RUB)')])
