# Generated by Django 4.0.1 on 2022-04-24 09:53

import bank.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Картка', max_length=100, verbose_name='назва банківського рахунку')),
                ('name', models.CharField(max_length=30, verbose_name="ім'я власника рахунку")),
                ('surname', models.CharField(max_length=30, verbose_name='прізвище власника рахунку')),
                ('patronymic', models.CharField(max_length=30, verbose_name='по-батькові власника рахунку')),
                ('iban', models.CharField(max_length=29, unique=True, verbose_name='iban')),
                ('currency', models.CharField(max_length=3)),
                ('money', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='електронна адреса')),
            ],
            options={
                'verbose_name': 'банківський рахунок',
                'verbose_name_plural': 'банківські рахунки',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Картка', max_length=100, verbose_name='назва картки')),
                ('account_iban', models.CharField(max_length=29, verbose_name='iban')),
                ('card_number', models.CharField(max_length=19, unique=True, verbose_name='номер картки')),
                ('expiry_date', models.CharField(max_length=5, verbose_name='термін дії')),
                ('payment_system', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=10, verbose_name='платіжна система')),
                ('cvv', models.CharField(max_length=3)),
                ('cardholder_name', models.CharField(max_length=30, verbose_name="ім'я власника картки")),
                ('cardholder_surname', models.CharField(max_length=30, verbose_name='прізвище власника картки')),
                ('cardholder_email', models.EmailField(max_length=254, null=True, verbose_name='електронна адреса власника картки')),
                ('color', models.CharField(choices=[('blue', 'Cиній'), ('cyan', 'Бірюзовий'), ('green', 'Зелений'), ('grey', 'Сірий'), ('magenta', 'Пурпурний'), ('orange', 'Оранжевий'), ('purple', 'Фіолетовий'), ('red', 'Червоний'), ('yellow', 'Жовтий')], default='blue', max_length=9, verbose_name='колір картки')),
            ],
            options={
                'verbose_name': 'картка',
                'verbose_name_plural': 'картки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='електронна адреса')),
                ('phone_number', models.CharField(max_length=13, unique=True, verbose_name='номер телефону')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name="ім'я")),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='по-батькові')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата приєднання')),
                ('is_staff', models.BooleanField(default=False, verbose_name='суперкористувач')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', bank.managers.UserManager()),
            ],
        ),
    ]
