# Generated by Django 4.0.1 on 2022-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='money',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.CharField(default=0, max_length=100, verbose_name='баланс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='валюта'),
        ),
    ]
