# Generated by Django 4.0.1 on 2022-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_bankaccount_money_bankaccount_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account_iban',
        ),
        migrations.AddField(
            model_name='card',
            name='bank_account',
            field=models.BigIntegerField(null=True, verbose_name='банківський рахунок'),
        ),
    ]
