# Generated by Django 4.0.1 on 2022-05-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_card_account_iban_card_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='баланс'),
        ),
    ]
