# Generated by Django 4.0.1 on 2022-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='дата')),
                ('rate', models.JSONField(verbose_name='курс обміну')),
            ],
            options={
                'verbose_name': 'Курс обміну',
                'verbose_name_plural': 'Курси обміну',
            },
        ),
    ]
