# Generated by Django 4.0.1 on 2022-05-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_bank_account', models.CharField(max_length=29, verbose_name='iban відправника')),
                ('receiver_bank_account', models.CharField(max_length=29, verbose_name='iban отримувача')),
                ('money', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='сума')),
                ('msg', models.CharField(max_length=100, verbose_name='повідомлення')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='час')),
                ('showing_to_sender', models.BooleanField(default=True, verbose_name='Показується для відправника')),
                ('showing_to_receiver', models.BooleanField(default=True, verbose_name='Показується для отримувача')),
            ],
            options={
                'verbose_name': 'транзакція',
                'verbose_name_plural': 'транзакції',
            },
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'курс обміну', 'verbose_name_plural': 'курси обміну'},
        ),
    ]
