# Generated by Django 4.0.1 on 2022-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_transaction_alter_exchangerate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='msg',
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(default='', max_length=100, verbose_name='коментар'),
            preserve_default=False,
        ),
    ]
