# Generated by Django 4.0.1 on 2022-05-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_transaction_msg_transaction_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='money',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_money',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=100, verbose_name='сума в валюті отримувача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_money',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=100, verbose_name='сума в валюті відправника'),
            preserve_default=False,
        ),
    ]
