# Generated by Django 4.0.1 on 2022-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='код підтвердження'),
        ),
    ]
