# Generated by Django 4.0.1 on 2022-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='код скидання паролю'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_request_time',
            field=models.DateTimeField(null=True, verbose_name='дата і час запиту на скидання паролю'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата і час приєднання'),
        ),
    ]
