# Generated by Django 4.0.1 on 2022-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_user_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_step_login',
            field=models.BooleanField(default=False, verbose_name='двоетапний вхід'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='номер картки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='код скидання паролю'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_request_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата і час запиту на скидання паролю'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='код підтвердження'),
        ),
    ]
