# Generated by Django 4.0.1 on 2022-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_user_two_step_login_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_step_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='код підтвердження входу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='код підтвердження електронної адреси'),
        ),
    ]
