# Generated by Django 4.0.1 on 2022-06-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_user_second_step_code_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_operation_confirmation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата і час останнього підтвердження операції'),
        ),
    ]
