# Generated by Django 4.0.1 on 2022-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_user_last_operation_confirmation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_operations',
            field=models.BooleanField(default=True, verbose_name='запитувати підтвердження важливих операцій'),
        ),
    ]
