# Generated by Django 4.0.1 on 2022-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_user_confirm_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_operations',
            field=models.CharField(choices=[(0, 'Завжди'), (30, 'Кожних 30с'), (60, 'Кожну хвилину'), (120, 'Кожні 2хв'), (300, 'Кожні 5хв'), (600, 'Кожні 10хв'), (None, 'Ніколи')], default=120, max_length=9, verbose_name='запитувати підтвердження важливих операцій'),
        ),
    ]
