# Generated by Django 4.0.1 on 2022-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_alter_user_confirm_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('cyan', 'Бірюзовий'), ('yellow', 'Жовтий'), ('green', 'Зелений'), ('orange', 'Помаранчевий'), ('magenta', 'Пурпурний'), ('blue', 'Cиній'), ('grey', 'Сірий'), ('purple', 'Фіолетовий'), ('red', 'Червоний')], default='blue', max_length=9, verbose_name='колір картки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='Картка', max_length=30, verbose_name='назва картки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_operations',
            field=models.CharField(blank=True, default=120, max_length=4, verbose_name='запитувати підтвердження важливих операцій'),
        ),
    ]
